---
# host group must be specified at command line, e.g.
# ansible-playbook configure.yml -e hosts=ec2hosts
- name: configuration
  hosts: "{{ hosts }}"
  user: ubuntu
  gather_facts: true
  vars:
    application:
      solr: False
      fedora: Flase
      frontend: True
  roles:
    - { role: packages } # Still working on this
    - { role: set_timezone }
    - { role: system_setup }
    - { role: capistrano_setup, when: application.frontend == True or application.solr == True }
    - { role: ruby, when: application.frontend == True }
    - { role: openjdk1_8, when: application.fedora == True or application.solr == True }
    - { role: fedora, when: application.fedora == True }
    - { role: solr, when: application.solr == True }
    - { role: frontend, when: application.frontend == True }
    # if using imagemagick and/or ffmpeg, uncomment:
    - { role: ffmpeg, when: application.frontend == True }
    - { role: imagemagick, when: application.frontend == True }
    - { role: sufia_dependencies/install, when: application.frontend == True }
    - { role: sufia_dependencies/config, when: application.frontend == True }
    # if using RIIIF, uncomment this role
    # - { role: RIIIF, when: application.frontend == True }
    - { role: webserver/install, when: application.frontend == True }
    - { role: webserver/config, when: application.frontend == True }
    - { role: app-config }
#    - { role: deploy, when: application.frontend == True or application.solr == True } #Still working on this
