---
# host group must be specified at command line, e.g.
# ansible-playbook configure.yml -e hosts=ec2hosts
- name: configuration
  hosts: "{{ hosts }}"
  user: ubuntu
  gather_facts: true
  vars:
    application:
      solr: True
      fedora: True
      frontend: True
  roles:
    - { role: packages }
    - { role: set_timezone }
    - { role: system_setup }
    - { role: capistrano_setup }
    - { role: ruby }
    - { role: openjdk1_8 }
    - { role: fedora, when: application.fedora == True }
    - { role: solr, when: application.solr == True }
    - { role: frontend, when: application.frontend == True }
    # if using imagemagick and/or ffmpeg, uncomment:
    # - { role: ffmpeg }
    # - { role: imagemagick }
    - { role: sufia_dependencies/install }
    - { role: sufia_dependencies/config }
    # if using RIIIF, uncomment this role
    # - { role: RIIIF }
    - { role: webserver/install }
    - { role: webserver/config }
    - { role: app-config }
    - { role: deploy }
