- hosts: localhost
  name: create
  connection: local
  gather_facts: False
  roles:
    - launch_ec2

- hosts: newboxes
  name: setup
  user: ubuntu
  gather_facts: true
  vars:
    ec2_vol_1: "{{ hostvars['localhost'].ec2_vol }}"
  roles:
    - { role: packages, sudo: yes }
    - { role: ec2, sudo: yes }

- include: configure.yml hosts=newboxes
