---
# ROLE: launch_ec2
# roles/launch_ec2/tasks/security_group.yml

  - name: Assign security rules
    ec2_group:
      name: '{{ internal_network }}'
      description: Internal networking
      aws_access_key: '{{ ec2_access_key }}'
      aws_secret_key: '{{ ec2_secret_key }}'
      region: '{{ ec2_region }}'
      vpc_id: '{{ vpc_id }}'
      state: present
      rules:
        - proto: tcp
          from_port: '{{ tomcat_port }}'
          to_port: '{{ tomcat_port }}'
          group_id: '{{ internal_network }}'

        - proto: tcp
          from_port: '{{ solr_port }}'
          to_port: '{{ solr_port }}'
          group_id: '{{ internal_network }}'

...
