---
# ROLE: launch_ec2
# roles/launch_ec2/tasks/security_group.yml
#
# Sets up the internal access rules for machines to have their roles broken out.
  - name: Build security group
    ec2_group:
      name: '{{ internal_network }}'
      description: Internal networking
      aws_access_key: '{{ ec2_access_key }}'
      aws_secret_key: '{{ ec2_secret_key }}'
      region: '{{ region }}'
      vpc_id: '{{ vpc_id }}'
      state: present
      rules:
      - proto: tcp
        from_port: 22
        to_port: 0.0.0.0/0
        group_id: '{{ internal_network }}'

      - proto: tcp
        from_port: '{{ fedora_port }}'
        to_port: '{{ fedora_port }}'
        group_id: '{{ internal_network }}'
          
      - proto: tcp
        from_port: '{{ solr_port }}'
        to_port: '{{ solr_port }}'
        group_id: '{{ internal_network }}'
    register: new_group

  - name: debug new_group
    debug: var=new_group
