---
# ROLE: launch_ec2
# roles/launch_ec2/tasks/main.yml
#
# Launches a new ec2 instance and attaches dedicated data volume

- name: Build internal and external security groups
  include: security_groups.yml

- name: Build EC2 machine(s)
  include: machine.yml
