---
# ROLE: launch_ec2
# roles/launch_ec2/tasks/security_group.yml
#
# Creates VPC security rules, internal and external
# allows single-machine or multipel-machine setups

- name: Build external security groups
  ec2_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    region: '{{ ec2_region }}'
    vpc_id: '{{ vpc_id }}'
    state: present
    rules:
      - proto: tcp
        from_port: '{{ item.open_from_port }}'
        to_port: '{{ item.open_to_port }}'
        cidr_ip: '{{ item.cidr_ip }}'
  with_items: "{{ external_security_groups }}"
  register: external_groups

- name: Build internal security groups
  ec2_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    region: '{{ ec2_region }}'
    vpc_id: '{{ vpc_id }}'
    state: present
    rules:
      - proto: tcp
        from_port: '{{ item.open_from_port }}'
        to_port: '{{ item.open_to_port }}'
        group_id: '{{ external_groups.results[0].group_id }}'
  with_items: "{{ vpc_security_groups }}"
