---
# ROLE: hydra-stack
# roles/hydra-stack/install/tasks/fedora.yml
#
- name: install servlet container package
  become: yes
  package: name={{ servlet }} state=present

- name: install additional centos tomcat packages
  become: yes
  package: name={{ item }} state=present
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps
  when: 
    - ansible_distribution == "CentOS"

- name: set tomcat to restart on reboot
  become: yes
  service: name={{ servlet }} enabled=yes
  when: 
    - ansible_distribution == "CentOS"

- name: download fedora
  become: yes
  get_url: url=https://github.com/fcrepo4/fcrepo4/releases/download/fcrepo-{{ fcrepo_version }}/fcrepo-webapp-{{ fcrepo_version }}.war owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} dest={{ install_path }}/fcrepo-webapp-{{ fcrepo_version }}.war timeout=100

- name: make fedora data dir
  file: owner={{ servlet }} group={{ servlet }} state=directory path=/opt/fedora-data
  become: yes

- name: check fedora.war
  become: yes
  stat: path={{ servlet_path }}/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  become: yes
  command: cp {{ install_path }}/fcrepo-webapp-{{ fcrepo_version }}.war {{ servlet_path }}/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: create tomcat config and java options for Fedora 4-4.5
  become: yes
  template: src=tomcat7.j2 dest="{{ fedora_config_file }}" backup=yes
  when: 
    - fcrepo_version | match("^4\.[0-5]\.[0-9]")

- name: create leveldb tomcat config and java options for Fedora 4.6-4.7
  become: yes
  template:
    src: tomcat7_leveldb.j2
    dest: "{{ fedora_config_file }}"
    owner: "{{ servlet }}"
    group: "{{ servlet }}"
    backup: yes
  when:
    - fcrepo_version | match("^4\.[6-9]\.[0-9]")
    - fedora_database == "file-simple"

- name: create leveldb tomcat config and java options for Fedora 4.6-4.7
  become: yes
  template:
    src: tomcat7_leveldb.j2
    dest: "{{ fedora_config_file }}"
    owner: "{{ servlet }}"
    group: "{{ servlet }}"
    backup: yes
  when:
    - fcrepo_version | match("^4\.[6-9]\.[0-9]")
    - fedora_database == "postgresql" OR "mysql"

- name: create mysql database:
  posgtresql_db:
    name: fcrepo
    encoding: utf8
    state: present
  when:
    - fedora_database == "mysql"

- name: create the fcrepo user for postgres
  postgresql_user:
    name: "{{ fcdb_user }}"
    password: "{{ fcdb_pass }}"
    state: present
    login_user: postgres
    login_host: "{{ fcdb_host }}"
    login_password: "{{ db_pass }}"
  when:
    - fedora_database == "postgresql"

- name: create fcrepo database:
  posgtresql_db:
    name: fcrepo
    encoding: UTF-8
    state: present
    owner: "{{ fcdb_user }}"
  when:
    - fedora_database == "postgresql"

- name: create the fcrepo user for mysql
  mysql_user:
    name: "{{ fcdb_user }}"
    password: "{{ fcdb_pass }}"
    state: present
    login_user: root
    login_host: "{{ fcdb_host }}"
    login_password: "{{ db_pass }}"
    priv: 'fcrepo.*:ALL'
  when:
    - fedora_database == "mysql"

- name: set port for tomcat
  become: yes
  replace:
    dest: /etc/{{ servlet }}/server.xml
    regexp: "8080"
    replace: "{{ tomcat_port }}"

- name: add log rotation for catalina.out (tomcat/fedora logs)
  become: yes
  template: src=logrotate-tomcat dest=/etc/logrotate.d/{{ servlet }} backup=yes

- name: restart servlet
  become: yes
  service: name={{ servlet }} enabled=yes state=restarted
