---
# ROLE: hydra-tutorials
# roles/hydra-tutorials/tasks/dive-into-hydra.yml
#
# Pre-load gem dependencies required by dive-into-hydra tutorial
#

- name: Install rails version 5.0.0.1 to use for Hydra tutorials
  command: "~/.rvm/bin/rvm all do gem install rails -v 5.0.0.1"

- name: generate demo app
  command: ".rvm/bin/rvm all do rails new cc-sample"

- name: add curation_concerns dependency to gemfile
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/cc-sample/Gemfile 
    state: present
    line: "gem 'curation_concerns', '1.6.1'"  
  
- name: install CC dependencies
  command: "~/.rvm/bin/rvm all do bundle install --gemfile ~/cc-sample/Gemfile" 
  
- name: pre-run the CC generator
  command: bash -lc "cd ~/cc-sample/ && rails generate curation_concerns:install -f"  

- name: pre-run the db migrations for CC
  command: bash -lc "cd ~/cc-sample/ && rails db:migrate"  
  
- name: set cc solr_wrapper download directory
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/cc-sample/.solr_wrapper
    state: present
    line: "download_dir: /var/tmp"

- name: set cc solr_wrapper to use 6.1.0
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/cc-sample/.solr_wrapper
    state: present
    line: "version: 6.1.0"

- name: set cc fcrepo_wrapper download directory
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/cc-sample/.fcrepo_wrapper
    state: present
    line: "download_dir: /var/tmp"

- name: set cc fcrepo_wrapper to use 6.1.0
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/cc-sample/.fcrepo_wrapper
    state: present
    line: "version: 4.5.1"
