---
# ROLE: hydra-stack
# roles/hydra-stack/install/tasks/main.yml
#
# installs solr and fedora in production mode as servlets under tomcat
#
- include: tomcat.yml
- include: solr_4.yml
  when: solr_version <= 4
- include: solr_5.yml
  when: solr_version >= 5
- include: fedora.yml
