---
# ROLE: hydra-stack
# roles/hydra-stack/install/tasks/main.yml
#
# installs solr and fedora in production mode as servlets under tomcat
#
- include: tomcat.yml
- include: solr_{{ solr_main_version }}.yml
- include: fedora.yml
