---
# ROLE: system_setup
# roles/system_setup/tasks/main.yml

# these two tasks ensure that the ansible_ssh_user will
# always belong to a group with the same name
- name: create install group
  become: yes
  group: name={{ ansible_ssh_user }} state=present

- name: create install user
  become: yes
  user: name={{ ansible_ssh_user }} groups={{ ansible_ssh_user }} shell=/bin/bash createhome=yes state=present

- name: chown /opt
  become: yes
  file: owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=directory path=/opt

- name: create install directory
  become: yes
  file: owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=directory path={{ install_path }}

- name: disable SELinux
  become: yes
  selinux: conf=/etc/selinux/config state=disabled
  when: ansible_distribution == "CentOS"

- name: update ssh config
  become: yes
  template: src=ssh_config dest=/etc/ssh/sshd_config backup=yes
  notify:
  - restart ssh service

- name: set rotation for system logs
  become: yes
  template: src=logrotate-sys.j2 dest=/etc/logrotate.d/rsyslog backup=yes

- name: Set hostname
  become: yes
  hostname: name={{ server_name }}

- name: Edit /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    state: present
    line: 127.0.0.1 {{ server_name }}
  when: ( server_name != "127.0.0.1")

- meta: flush_handlers
