---

- name: configure ImageMagick
  shell: cd {{ im_dir }} && ./configure --prefix=/usr/local --with-modules=yes

- name: make ImageMagick
  shell: cd {{ im_dir }} && make 

- name: install ImageMagick
  become: yes
  shell: cd {{ im_dir }} && make install

- name: link new ImageMagick
  become: yes
  shell: ldconfig

- name: configure policy.xml
  become: yes
  lineinfile:
    dest: "{{ imagemagick_config_path }}/policy.xml"
    line: "{{ item }}"
    state: present
    insertbefore: </policymap>
  with_items:
      - '  <policy domain="coder" rights="none" pattern="EPHEMERAL" />'
      - '  <policy domain="coder" rights="none" pattern="HTTPS" />'
      - '  <policy domain="coder" rights="none" pattern="MVG" />'
      - '  <policy domain="coder" rights="none" pattern="MSL" />'
      - '  <policy domain="coder" rights="none" pattern="TEXT" />'
      - '  <policy domain="coder" rights="none" pattern="SHOW" />'
      - '  <policy domain="coder" rights="none" pattern="WIN" />'
      - '  <policy domain="coder" rights="none" pattern="PLT" />'
